apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-user
data:
  lb_auth_issuer_uri: "http://172.17.93.241:32560"
  lb_user_uri: "http://172.17.93.241:31179"
  port: "8081"
  db_host: "mysql8:3306"
  db_database: "mcsv_user"
  course_url: "http://msvc-cursos:8082/api/v1/courses/"
  profile: "dev"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-courses
data:
    port: "8082"
    db_host: "postgres14:5432"
    db_database: "msvc_courses"
    user_url: "http://user-microservice:8081/api/v1/user/"
